# Generated by Django 6.0.3 on 2026-06-25 17:23

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
