# Generated by Django 6.0.3 on 2026-07-04 08:15

from django.db import migrations
from django.db.models import Q


def backfill_available(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    # Mark available=True where stock > 0
    Product.objects.filter(stock__gt=0).update(available=True)
    # Mark available=False where stock == 0
    Product.objects.filter(stock=0).update(available=False)


def reverse_backfill(apps, schema_editor):
    pass  # No meaningful reverse — leave data as-is


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sync_available_from_stock'),
    ]

    operations = [
        migrations.RunPython(backfill_available, reverse_backfill),
    ]
