# Generated by Django 6.0.3 on 2026-08-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Store flexible product details like weight, dimensions, quantity, etc.'),
        ),
    ]
