# Generated by Django 6.0.3 on 2026-07-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
