# Generated by Django 6.0.3 on 2026-08-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier'), ('visitor', 'Visitor')], default='visitor', max_length=50),
        ),
    ]
